-- PostgreSQL initialization script (legacy option)
-- Usage:
--   psql -U postgres -f init-db-postgresql.sql

DROP DATABASE IF EXISTS messagerie_association;
CREATE DATABASE messagerie_association;
\c messagerie_association;

-- Tables can be generated by Hibernate with hbm2ddl.auto=update
-- or created manually if needed.
